seed: 8888

data:
  name: celeba
  root: ~/data/CelebA/
  img_size: 64

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

encoder:
  target: models.autoencoder.simple_cnn.Encoder
  params:
    img_channels: 3
    hidden_dim: 256
    n_resblocks: 2

decoder:
  target: models.autoencoder.simple_cnn.Decoder
  params:
    img_channels: 3
    hidden_dim: 256
    n_resblocks: 2

quantizer:
  target: models.quantizer.VectorQuantizer
  params:
    codebook_num: 512
    codebook_dim: 64
    l2_norm: false
    use_ema_update: false
    ema_decay: 0.99
    use_entropy_reg: false
    entropy_reg_temp: 0.01

train:
  n_steps: 500000
  batch_size: 256

  coef_commit: 0.25
  coef_entropy: 0.0

  print_freq: 100
  sample_freq: 10000
  save_freq: 10000

  optim:
    target: torch.optim.Adam
    params:
      lr: 0.0004
