seed: 8888

data:
  name: imagenet
  root: ~/data/ImageNet/ILSVRC2012/Images
  img_size: 64
  crop: random

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

encoder:
  target: models.autoencoder.simple_cnn.Encoder
  params:
    img_channels: 3
    hidden_dim: 256
    n_resblocks: 2

decoder:
  target: models.autoencoder.simple_cnn.Decoder
  params:
    img_channels: 3
    hidden_dim: 256
    n_resblocks: 2

quantizer:
  target: models.quantizer.LookupFreeQuantizer
  params:
    dim: 9  # codebook size = 2 ** 9 = 512
    use_entropy_reg: true
    entropy_reg_temp: 0.01

train:
  n_steps: 500000
  batch_size: 256

  coef_commit: 0.25
  coef_entropy: 0.1  # TODO: the original paper uses an annealing schedule

  print_freq: 100
  sample_freq: 10000
  save_freq: 10000

  optim:
    target: torch.optim.Adam
    params:
      lr: 0.0004
