seed: 8888

data:
  name: imagenet
  root: ~/data/ImageNet/ILSVRC2012/Images
  img_size: 256
  crop: random

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

encoder:
  target: models.autoencoder.vqgan_net.Encoder
  params:
    in_channels: 3
    z_channels: 256
    dim: 128
    dim_mults: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    dropout: 0.0

decoder:
  target: models.autoencoder.vqgan_net.Decoder
  params:
    out_channels: 3
    z_channels: 256
    dim: 128
    dim_mults: [1, 1, 2, 2, 4, 4]
    num_res_blocks: 2
    dropout: 0.0

quantizer:
  target: models.quantizer.ResidualQuantizer
  params:
    depth: 4
    codebook_num: 16384
    codebook_dim: 256

disc:
  target: models.discriminator.patchgan.PatchGANDiscriminator
  params:
    in_channels: 3
    dim: 64
    n_layers: 3

train:
  n_steps: 100000
  batch_size: 128
  micro_batch_size: ~

  type_rec: l2
  coef_rec: 1.00
  coef_lpips: 1.00
  coef_commit: 0.25
  coef_adv: 0.75
  start_adv: 0
  adaptive_adv_weight: True

  print_freq: 500
  sample_freq: 5000
  save_freq: 20000

  optim:
    target: torch.optim.Adam
    params:
      lr: 0.00004
      betas: [0.5, 0.9]

  optim_d:
    target: torch.optim.Adam
    params:
      lr: 0.00004
      betas: [0.5, 0.9]
