seed: 8888

data:
  name: imagenet
  root: ~/data/ImageNet/ILSVRC2012/Images
  img_size: 256
  crop: random

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2

encoder:
  target: models.autoencoder.titok_net.Encoder
  params:
    in_channels: 3
    image_size: 256
    patch_size: 16
    embed_dim: 768  # base
    n_heads: 12     # base
    n_layers: 12    # base
    n_tokens: 64

decoder:
  target: models.autoencoder.titok_net.Decoder
  params:
    out_channels: 3
    image_size: 256
    patch_size: 16
    embed_dim: 768  # base
    n_heads: 12     # base
    n_layers: 12    # base
    n_tokens: 64

quantizer:
  target: models.quantizer.VectorQuantizer
  params:
    codebook_num: 4096
    codebook_dim: 12
    l2_norm: True

disc:
  target: models.discriminator.TitokGANDiscriminator

train:
  n_steps: 1000000
  batch_size: 256
  micro_batch_size: ~

  type_rec: l2
  coef_rec: 1.0

  coef_lpips: 1.0

  type_perc: convnext_s
  coef_perc: 0.1

  coef_commit: 0.25
  coef_vq: 1.0

  coef_adv: 0.1
  start_adv: 200000
  coef_lecam_reg: 0.001

  ema:
    decay: 0.9999
    ema_warmup_type: crowsonkb

  clip_grad_norm: 1.0

  print_freq: 500
  sample_freq: 10000
  save_freq: 50000

  optim:
    target: torch.optim.AdamW
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      weight_decay: 0.0001

  optim_d:
    target: torch.optim.AdamW
    params:
      lr: 0.0001
      betas: [0.9, 0.999]
      weight_decay: 0.0001

  sched:
    target: utils.scheduler.CosineMinimumWarmupLR
    params:
      warmup_steps: 10000
      training_steps: 1000000
      min_lr: 0.00001
